[package]
name = "jiro"
version = "0.1.0"
authors = ["Liam Avella-Pisera"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "jiro"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "^4"

[dev-dependencies]
reqwest = "0.11.4"